{"name": "test_check_instagram", "status": "failed", "statusDetails": {"message": "AssertionError: assert 301 == 200\n +  where 301 = <bound method Home.check_social_media of <Pages.homePage.Home object at 0x7f97494006a0>>('/html/body/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[1]/a[4]')\n +    where <bound method Home.check_social_media of <Pages.homePage.Home object at 0x7f97494006a0>> = <Pages.homePage.Home object at 0x7f97494006a0>.check_social_media\n +      where <Pages.homePage.Home object at 0x7f97494006a0> = Home(<selenium.webdriver.chrome.webdriver.WebDriver (session=\"e4b26398b45304dff06af30140215549\")>)\n +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e4b26398b45304dff06af30140215549\")> = <tests.test_social_media.TestSocialMedia object at 0x7f9749398820>.driver\n +    and   '/html/body/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[1]/a[4]' = Locators.instagram", "trace": "self = <tests.test_social_media.TestSocialMedia object at 0x7f9749398820>\n\n    @pytest.mark.social_media\n    def test_check_instagram(self):\n>       assert Home(self.driver).check_social_media(Locators.instagram) == 200\nE       assert 301 == 200\nE        +  where 301 = <bound method Home.check_social_media of <Pages.homePage.Home object at 0x7f97494006a0>>('/html/body/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[1]/a[4]')\nE        +    where <bound method Home.check_social_media of <Pages.homePage.Home object at 0x7f97494006a0>> = <Pages.homePage.Home object at 0x7f97494006a0>.check_social_media\nE        +      where <Pages.homePage.Home object at 0x7f97494006a0> = Home(<selenium.webdriver.chrome.webdriver.WebDriver (session=\"e4b26398b45304dff06af30140215549\")>)\nE        +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e4b26398b45304dff06af30140215549\")> = <tests.test_social_media.TestSocialMedia object at 0x7f9749398820>.driver\nE        +    and   '/html/body/div[2]/div[1]/div[2]/div[1]/div/div/div[3]/div/div[1]/a[4]' = Locators.instagram\n\ntests/test_social_media.py:15: AssertionError"}, "start": 1662272263176, "stop": 1662272265579, "uuid": "55792880-465b-4d77-9819-3ee569c64d72", "historyId": "6aecfb3fd6d36bd94578abb01ae0d358", "testCaseId": "0197e4ff4bd19694f8bf82b88faa0b24", "fullName": "tests.test_social_media.TestSocialMedia#test_check_instagram", "labels": [{"name": "tag", "value": "social_media"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_social_media"}, {"name": "subSuite", "value": "TestSocialMedia"}, {"name": "host", "value": "walker"}, {"name": "thread", "value": "41695-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_social_media"}]}